var villageData = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { 
	"CITY": "Laceiras", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["laceiras-1.jpg", "laceiras-2.jpg","laceiras-3.jpg","laceiras-4.jpg"], 
	"DESCRIPTION_EN": "The village (altitude 794m) which contains 16 houses is set aside in 2 sites divided by the main road and it is located very close to the Castle. The road crosses a small creek. The parking is very limited.", 
	"DESCRIPTION_P": "A Aldeia (altitude 794m) encontra-se dividida em duas partes pela estrada principal. Está muito próxima do castelo de Castro e tem vista para o mesmo. O acesso é feito por um caminho que cruza uma corga. O estacionamento é muito limitado. A aldeia tem 16 casas.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "0", 
	"HP": "2", 
	"TER": "0", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.164962,42.017547 ] } }, 
{ "type": "Feature", "properties": { 
	"CITY": "Bago", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["bago-1.jpg", "bago-2.jpg","bago-3.jpg","bago-4.jpg","bago-5.jpg"], 
	"DESCRIPTION_EN": "The village is located at the ridge of a mountain (altitude 764m) on the left bank of the Rio Laboreiro, it is located central to the valley and exposed to the south side. The village has 31 houses and it is served by public water service.", 
	"DESCRIPTION_P": "A aldeia fica na crista de um afloramento rochoso (altitude 764m) na margem esquerda do Rio Laboreiro. Encontra-se no centro no vale e com exposição ao quadrante sul. A aldeia tem 31 casas. É abastecida pela rede de água pública.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "0", 
	"HP": "0", 
	"TER": "0", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.159323,41.996465 ] } },
{ "type": "Feature", "properties": { 
	"CITY": "Curveira", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["curveira-1.jpg", "curveira-2.jpg","curveira-3.jpg","curveira-4.jpg","curveira-5.jpg"], 
	"DESCRIPTION_EN": "The village of Curveira (altitude 839m) is set on the left bank of Laboreiro river on a flatland. The original part of the village develops along the east-west axis which ends by a creek in a flatland. The village has 37 houses and it is inhabited. It is served by public water system.", 
	"DESCRIPTION_P": "A aldeia de Curveira (altitude 839m) está localizada na margem esquerda do Rio Laboreiro. A parte mais antiga da aldeia desenvolve-se ao longo de um eixo poente-nascente numa zona relativamente plana. A nascente é limitada por uma corga. A aldeia tem 37 casas e é habitada. É abastecida pela rede de água pública.", 
	"MORE": '<img id="thumbImg" onclick="showImage();" src="./img/sale/Curveira/map.jpg" alt="House for sale / casas a venda" width="500px"><div id="villageMoreContent"><p><b>Description / Descrição:</b></p><p>Two-stories house in granite with tile roof</p><p>Casa em granito com cobertura em telha.</p><p><b>Contact owner / Contato proprietário:</b></p><p> +351 251 466 074/+351 967 228 380</p></div>',
	"CF": "0", 
	"HP": "0", 
	"TER": "1", 
	"AL": "1" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.151785,42.012800 ] } },
{ "type": "Feature", "properties": { 
	"CITY": "Ramisqueira", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["ramisqueira-1.jpg","ramisqueira-2.jpg","ramisqueira-3.jpg"], 
	"DESCRIPTION_EN": "The village of Ramisqueira (altitude 795m) is close to a oak forest where a trail leads to a dam/ pool. The village has 11 houses among which lodging. Nearby there is also a house which belonged to a forest ranger.", 
	"DESCRIPTION_P": "A aldeia da Ramisqueira (altitude 795m) está próxima de um carvalhal e possui um trilho em bom estado que dá acesso a um açude/ lagoa. A aldeia tem 11 casas, inclusive  alojamento turistico. Perto encontra-se uma casa de guarda florestal.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "0", 
	"HP": "0", 
	"TER": "1", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.167229,42.012909 ] } },
{ "type": "Feature", "properties": { 
	"CITY": "João Alvo", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["joao-alvo-1.jpg","joao-alvo-2.jpg","joao-alvo-3.jpg","joao-alvo-4.jpg","joao-alvo-5.jpg"], 
	"DESCRIPTION_EN": "The village of Joao Alvo is close to an oak forest. It has 7 houses, among which lodging. The parking area is very limited.", 
	"DESCRIPTION_P": "A aldeia de João Alvo está próxima de um carvalhal. Tem 7 casas situadas, inclusive alojamento turistico. O espaço de estacionamento é muito limitado.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "1", 
	"HP": "0", 
	"TER": "3", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.166575, 42.009725  ] } },
{ "type": "Feature", "properties": { 
	"CITY": "Barreiro", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["barreiro-1.jpg","barreiro-2.jpg","barreiro-3.jpg","barreiro-4.jpg"], 
	"DESCRIPTION_EN": "The village of Barreiro (altitude 841m) has 2 sites and a total of 38 houses. Both sites are distant from the main road and are served by the public water system. The south site is called Ponte do Barreiro and includes lodging.", 
	"DESCRIPTION_P": "A aldeia do Barreiro (altitude 841m) tem dois nucleos e possui 38 casas. Ambos estão relativamente distantes da estrada principal e têm acesso a água da rede pública. O nucleo a sul chamado Ponte do Barreiro inclui alojamento turistico.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "4", 
	"HP": "0", 
	"TER": "0", 
	"AL": "1" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.170578, 42.007722  ] } }, 
{ "type": "Feature", "properties": { 
	"CITY": "Assureira", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["assureira-1.jpg","assureira-2.jpg","assureira-3.jpg","assureira-4.jpg","assureira-5.jpg","assureira-6.jpg"], 
	"DESCRIPTION_EN": "The village of Assureira (altitude 771m) is close to the New Bridge, under which there is a natural pool very popular in the summer. The village has 20 houses, and is inhabited.", 
	"DESCRIPTION_P": "A aldeia da Assureira (altitude 771m) está perto da Ponte Nova, local de grande afluência balnear no Verão. A aldeia contém 20 casas e é habitada.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>",
	"CF": "0", 
	"HP": "1", 
	"TER": "0", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.166330, 42.002396] } }, 
{ "type": "Feature", "properties": { 
	"CITY": "Podre", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["podre-1.jpg","podre-2.jpg","podre-3.jpg","podre-4.jpg"], 
	"DESCRIPTION_EN": "The village of Podre is quite distant from the main road. It is located next to a oak forest with the oldest oak tree in the region. It has 13 houses and lodging and its served by the public water network.", 
	"DESCRIPTION_P": "A aldeia da Podre encontra-se distante da estrada principal. Encontra-se perto de um carvalhal, junto ao carvalho centenário, mais antigo do vale. Tem 13 casas e alojamento turistico e é abastecida pela rede publica de água.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>", 
	"CF": "0", 
	"HP": "0", 
	"TER": "0", 
	"AL": "2"  }, 
	"geometry": { "type": "Point", "coordinates": [ -8.168519, 42.002793 ] } },
{ "type": "Feature", "properties": { 
	"CITY": "Alagoa", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["alagoa-1.jpg","alagoa-2.jpg"], 
	"DESCRIPTION_EN": "The village of Alagoa (altitude 844m) is located on the road to Ribeiro and its close to a oak forest. The village has 14 houses and lodging. There is limited parking space.", 
	"DESCRIPTION_P": "A aldeia de Alagoa (altitude 844m) encontra-se na estrada para o Ribeiro e está próxima do carvalhal. A aldeia contém 14 casas e alojamento turistico. O estacionamento é muito limitado.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>",
	"CF": "0", 
	"HP": "0", 
	"TER": "1", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.171196, 41.993746 ] } },
{ "type": "Feature", "properties": { 
	"CITY": "Entalada", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["entalada-1.jpg","entalada-2.jpg","entalada-3.jpg","entalada-4.jpg","entalada-5.jpg"], 
	"DESCRIPTION_EN": "The village of Entalada (altitude 847m) is located on the road to Ribeiro. It has 18 houses including lodging and parking space within the village.", 
	"DESCRIPTION_P": "A aldeia da Entalada (altitude 847m) encontra-se na estrada para o Ribeiro. Tem 18 casas e alojamento turistico. Existe estacionamento dentro da aldeia.", 
	"MORE": '<img id="thumbImg" onclick="showImage();" src="./img/sale/Entalada/map.jpg" alt="Houses for sale / casas a venda" width="500px"><div id="villageMoreContent"><p><b>Description / Descrição:</b></p><p>Both houses are located in the central cluster. Top: House with 2 stories, a porch and a patio. Bottom: House with two stories and a patio.</p><p>Ambas as casas estão localizadas no cluster central. Acima: Casa com 2 pisos, varanda e patio. Abaixo: Casa com 2 andares e um patio.</p><p><b>Contact owner / Contato proprietário:</b></p><p>+351 933375915</p></div>',
	"CF": "1", 
	"HP": "3", 
	"TER": "1", 
	"AL": "1" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.170385, 41.988499 ] } }, 
{ "type": "Feature", "properties": { 
	"CITY": "Dorna", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["dorna-1.jpg","dorna-2.jpg","dorna-3.jpg"], 
	"DESCRIPTION_EN": "The village is located on a flatland in the valley, next to the bridge of Dorna and the dam of Dorna. It has 28 houses, all derelict.", 
	"DESCRIPTION_P": "A aldeia encontra-se no fundo do vale numa área plana, próxima da ponte de Dorna e do pantano de Pontes. Possui 28 casas, todas abandonadas.", 
	"MORE": '<img id="thumbImg" onclick="showImage();" src="./img/sale/Dorna/map.jpg" alt="House for sale / casas a venda" width="500px"><div id="villageMoreContent"><p><b>Description / Descrição:</b></p><p>The house is located in the outer cluster. It is 2 stories high.</p><p>Casa localizada no nucleo periferico da aldeia. Tem 2 pisos.</p><p><b>Contact owner / Contato proprietário:</b></p><p>+351 251404602</p></div>',
	"CF": "0", 
	"HP": "0", 
	"TER": "0", 
	"AL": "0"  }, 
	"geometry": { "type": "Point", "coordinates": [ -8.169566, 41.991940 ] } },  
{ "type": "Feature", "properties": { 
	"CITY": "Mareco", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["mareco-1.jpg"], 
	"DESCRIPTION_EN": "The village of Mareco is located on a flatland of the valley (altitude 747m), south of the Mareco bridge. It has a milder climate suitable for growing vegetables. It is close to the border with Spain and has parking space at the entry of the village. The village has 32 houses and it is inhabited.", 
	"DESCRIPTION_P": "A aldeia do Mareco encontra-se na zona mais plana do vale (altitude 747m), a sul da ponte do Mareco. Tem um clima mais brando que permite a produção de hortícolas. Está muito próxima da fronteira e possui estacionamento à entrada da aldeia. A aldeia tem 32 casas e é habitada.", 
	"MORE": "<p>No houses for sale available.</p><p>Nenhuma informação adicional disponível.</p>",
	"CF": "0", 
	"HP": "5", 
	"TER": "0", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.165348, 41.982976 ] } },  
{ "type": "Feature", "properties": { 
	"CITY": "Pontes", 
	"COUNTRY": "Portugal", 
	"IMAGE": ["pontes-1.jpg","pontes-2.jpg","pontes-3.jpg"], 
	"DESCRIPTION_EN": "The village of Pontes is located in the lowest point of the valley (altitude 725m), on the way to the border with Spain. It is close to the river Laboreiro. Its cropfields used to be irrigated by an aqueduct connected to a dam near Dorna. The village is served by public water and has its own sewage system. The village has 22 houses including lodging.", 
	"DESCRIPTION_P": "A aldeia de Pontes está situada no ponto mais baixo do vale (altitude 725 m), a caminho da fronteira da Ameixoeira, estando muito próxima do rio Laboreiro. Possui um aqueduto em desuso que foi em tempo servido pelo pantano de Pontes/ Dorna, conduzindo a água para os campos. A aldeia é servida por rede pública de água. Possui 22 casas inclusive alojamento turistico.", 
	"MORE": '<img id="thumbImg" onclick="showImage();" src="./img/sale/Pontes/map.jpg" alt="Houses for sale / casas a venda" width="500px"><div id="villageMoreContent"><p><b>Description / Descrição:</b></p><p>Top: The house is located in the central cluster near the communitarian oven. The house used to be a barn. The house is two stories high and its floor area is 400m². It is made of granite blocks. The roof structure is made of oak wood and covered in ceramic roof tile. Bottom: This house is located in the outer cluster. It is 2 story high and its floor area is 100m². It is made of granite blocks and has a tile roof.</p><p>Acima: A casa palheiro encontra-se no nucleo central de Pontes perto do forno comunitário. A casa tem 2 pisos e 400m² de area util. Foi construida em blocos de granito e telhado de telha ceramica com estrutura de carvalho. Para mais informações contactar Ecotura. Abaixo: A casa encontra-se no núcleo de entrada da aldeia. A casa tem dois pisos e 100m² de area util. Encontra-se em bom estado de conservação.</p><p><b>Contact owner / Contato proprietário:</b></p><p>N.A.</p></div>',
	"CF": "0", 
	"HP": "0", 
	"TER": "3", 
	"AL": "0" }, 
	"geometry": { "type": "Point", "coordinates": [ -8.163534, 41.988626 ] } }  
]
};


 


