var villageData = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "CITY": "Laceiras", "COUNTRY": "Portugal", "IMAGE": ["laceiras-1.jpg", "laceiras-2.jpg","laceiras-3.jpg","laceiras-4.jpg"], "DESCRIPTION": "A Aldeia econtra-se dividade em duas partes pela estrada principal. Está muito próxima do castelo de Castro e tem vista para o mesmo. O acesso é feito por um caminho empedrado que cruza uma corga. O estacionamento só é possivel na estrada principal. Contém 16 casas, tendo 2 casas de férias. Não inclui nenhum alojamento turistico.", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "2", "TER": "0", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.164962,42.017547 ] } }, 
{ "type": "Feature", "properties": { "CITY": "Ramisqueira", "COUNTRY": "Portugal", "IMAGE": ["ramisqueira-1.jpg","ramisqueira-2.jpg"], "DESCRIPTION": "A aldeia da Ramisqueira está próxima de um carvalhal e possui um trilho em bom estado que dá acesso ao pantano da Ramisqueira a poente da aldeia. A aldeia tem 11 casas e um alojamento turistico. Tem ainda perto uma casa florestal desactivada.", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "0", "TER": "1", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.167229,42.012909 ] } },
{ "type": "Feature", "properties": { "CITY": "João Alvo", "COUNTRY": "Portugal", "IMAGE": ["joao-alvo-1.jpg"], "DESCRIPTION": "A aldeia de João Alvo tem 7 casas situadas perto de um carvalhal. Tem 2 alojamentos turisticos e uma casa de férias. O estacionamento encontra-se no caminho de acesso.", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "1", "TER": "3", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.166575, 42.009725  ] } },
{ "type": "Feature", "properties": { "CITY": "Barreiro", "COUNTRY": "Portugal", "IMAGE": ["barreiro-1.jpg","barreiro-2.jpg","barreiro-3.jpg","barreiro-4.jpg"], "DESCRIPTION": "A aldeia do Barreiro tem dois nucleos e possui 38 casas e 4 casas de férias. O nucleo a sul  chamado Ponte do Barreiro tem um alojamento turistico. A aldeia está relativamente distante da estrada principal. Tem 1 casa à venda.<br>Contacto: +251 966127851", "MORE": "Nenhuma informação adicional disponível", "CF": "4", "HP": "0", "TER": "0", "AL": "1" }, "geometry": { "type": "Point", "coordinates": [ -8.170578, 42.007722  ] } }, 
{ "type": "Feature", "properties": { "CITY": "Assureira", "COUNTRY": "Portugal", "IMAGE": ["assureira-1.jpg","assureira-2.jpg","assureira-3.jpg"], "DESCRIPTION": "A aldeia da Assureira está perto da Ponte Nova, local de grande afluência balnear no Verão. A aldeia contém 20 casas, uma das quais se encontra habitada. Tem 1 casa à venda.<br>Contacto: +251 966127851", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "1", "TER": "0", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.166330, 42.002396] } }, 
{ "type": "Feature", "properties": { "CITY": "Podre", "COUNTRY": "Portugal", "IMAGE": ["podre-1.jpg"], "DESCRIPTION": "A aldeia da Podre encontra-se distante da estrada principal. Encontra-se perto de um carvalhal, junto ao carvalho centenário, mais antigo do vale. Tem 13 casas entre as quais duas casas de férias.", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "0", "TER": "1", "AL": "1"  }, "geometry": { "type": "Point", "coordinates": [ -8.168519, 42.002793 ] } },
{ "type": "Feature", "properties": { "CITY": "Alagoa", "COUNTRY": "Portugal", "IMAGE": ["alagoa-1.jpg","alagoa-2.jpg"], "DESCRIPTION": "A aldeia de Alagoa encontra-se na estrada para o Ribeiro e está próxima do carvalhal. A aldeia contém 14 casas. Possui um alojamento turistico e 1 casa de férias. O estacionamento tem que ser feito na estrada do Ribeiro. Tem ainda uma ponte que atravessa uma corga.", "MORE": "Nenhuma informação adicional disponível", "CF": "1", "HP": "0", "TER": "1", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.171196, 41.993746 ] } },
{ "type": "Feature", "properties": { "CITY": "Entalada", "COUNTRY": "Portugal", "IMAGE": ["entalada-1.jpg","entalada-2.jpg"], "DESCRIPTION": "A aldeia da Entalada encontra-se a meia encosta na estrada para o Ribeiro de Baixo. Tem 18 casas, entre as quais 3 casas de férias e 2  alojamentos turisticos. Tem estacionamento dentro da aldeia. Tem 1 casa à venda (ver foto).<br>Contacto: +251 258250963", "MORE": "Nenhuma informação adicional disponível", "CF": "1", "HP": "3", "TER": "1", "AL": "1" }, "geometry": { "type": "Point", "coordinates": [ -8.170385, 41.988499 ] } }, 
{ "type": "Feature", "properties": { "CITY": "Dorna", "COUNTRY": "Portugal", "IMAGE": ["dorna-1.jpg","dorna-2.jpg","dorna-3.jpg","dorna-4.jpg"], "DESCRIPTION": "A aldeia econtra-se no fundo  do vale numa área plana, próxima da ponte de Dorna e do pantano de Pontes. Possui 28 casas todas abandonadas. Tem 1 casa à venda.<br>Contacto: +251404602", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "0", "TER": "0", "AL": "0"  }, "geometry": { "type": "Point", "coordinates": [ -8.169566, 41.991940 ] } },  
{ "type": "Feature", "properties": { "CITY": "Mareco", "COUNTRY": "Portugal", "IMAGE": ["mareco-1.jpg"], "DESCRIPTION": "A aldeia do Mareco encontra-se no vale, próxima da ponte do Mareco. Tem um clima mais brando que permite a produção de hortícolas. Está muito próxima da fronteira e possui estacionamento à entrada a aldeia. A aldeia tem 32 casas, entre as quais 5 casas de habitação permanente.", "MORE": "Nenhuma informação adicional disponível", "CF": "0", "HP": "5", "TER": "0", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.165348, 41.982976 ] } },  
{ "type": "Feature", "properties": { "CITY": "Pontes", "COUNTRY": "Portugal", "IMAGE": ["pontes-1.jpg","pontes-2.jpg","pontes-3.jpg"], "DESCRIPTION": "A aldeia de Pontes está situada no vale, a caminho da fronteira da Ameixoeira, estando muito próxima do rio Laboreiro. Possui aqueduto em desuso que foi em tempo servido pelo pantano de Pontes/Dorna. A aldeia é servida por rede pública de água. Possui 22 casas, entre os quais 3 alojamentos turisticos. Tem 1 casa à venda.", "MORE": '<img id="thumbImg" onclick="showImage();" src="./img/read-more/Pontes/map.jpg" alt="Localização das duas casas. Acima: A casa do palheiro. Abaixo: A casa na entrada." width="500px"><div id="villageMoreContent"><p><b>A casa do palheiro:</b></p><p>A casa palheiro encontra-se no nucleo central de Pontes perto do forno comunitário dentro do pátio localizado a sul da mesma.A casa tem 400m² de area util, e dois pisos. Encontra-se em bom estado de conservação. Para mais informações contactar Ecotura.</p><p><b>A casa na entrada:</b></p><p>A casa encontra-se no nucleo de entrada de Pontes. A casa tem 100m² de area util, e dois pisos. Encontra-se em bom estado de conservação.</p></div>', "CF": "0", "HP": "0", "TER": "3", "AL": "0" }, "geometry": { "type": "Point", "coordinates": [ -8.163534, 41.988626 ] } }  
]
};


 


